spring:
  application:
    name: canal-client

server:
  port: 8080

canal:
  server: 127.0.0.1
  port: 11111
  listenList:
    - destination: example
      subscribe: .*..
    - destination: example2
      subscribe: .*..